from copilot.models.bronze import BronzeGenerationResponse

class ProjectGenerator:
    """Generate project files from a Bronze Response."""

    @staticmethod
    def generate_files(
        response: BronzeGenerationResponse,
    ) -> dict[str, str]:
        """Return generated project files."""

        return {
            "customer_ingestion.py": response.python_code,
            "bronze_table.sql": response.sql_code,
            "README.md": (
                "# Bronze Pipeline\n\n"
                "Generated by Enterprise Engineering Copilot.\n"
            ),
            "quality_rules.txt": "\n".join(
                response.quality_rules
            ),
            "assumptions.txt": "\n".join(
                response.assumptions
            ),
        }