from copilot.models.bronze import (
    BronzeGenerationRequest,
    BronzeGenerationResponse,
)


class ProjectGenerator:
    """Generate project files from a Bronze Response."""

    @staticmethod
    def generate_files(
        request: BronzeGenerationRequest,
        response: BronzeGenerationResponse,
        generated_test: str,
    ) -> dict[str, str]:
        """Return generated project files."""

        pipeline_name = (
            request.api_name.strip()
            .lower()
            .replace(" api", "")
            .replace(" ", "_")
        )

        if not pipeline_name:
            pipeline_name = "bronze_pipeline"

        pipeline_file = f"{pipeline_name}_ingestion.py"
        test_file_name = f"test_{pipeline_name}_ingestion.py"

        readme = f"""# {request.api_name} Bronze Pipeline

Generated by Enterprise Engineering Copilot.

## API

{request.api_name}

## Endpoint

{request.endpoint}

## Authentication

{request.authentication}

## Description

{request.description}

## Generated Files

- src/{pipeline_file} - Bronze ingestion pipeline
- tests/{test_file_name} - AI-generated pytest unit tests
- pyproject.toml - Project metadata and dependencies
- sql/bronze_table.sql - Delta table definition
- config/config.yaml - Project configuration
- requirements.txt - Python dependencies
- .gitignore - Git ignore rules
- .github/workflows/ci.yml - GitHub Actions workflow for automated testing
- config/quality_rules.txt - Data quality checks
- config/assumptions.txt - Pipeline assumptions

## Summary

{response.summary}
"""

        pyproject = f"""[project]
name = "{pipeline_name}"
version = "0.1.0"
description = "{request.description}"
requires-python = ">=3.11"

dependencies = [
    "requests",
    "pydantic",
    "tenacity",
    "pyspark",
    "pytest",
    "delta-spark",
    "databricks-sdk",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
"""

        config = f"""api:
  name: {request.api_name}
  endpoint: {request.endpoint}
  authentication: {request.authentication}

bronze:
  catalog: default
  schema: bronze
  table: {pipeline_name}

retry:
  max_attempts: 3
  backoff_seconds: 5
"""

        requirements = """requests
pydantic
tenacity
pyspark
delta-spark
databricks-sdk
pytest
"""

        gitignore = """__pycache__/
*.pyc
.pytest_cache/
.coverage
htmlcov/

.venv/
.env

.vscode/
.idea/

dist/
build/

*.log
"""

        ci_workflow = """name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
"""

        project_root = pipeline_name

        return {
            f"{project_root}/README.md": readme,
            f"{project_root}/pyproject.toml": pyproject,
            f"{project_root}/requirements.txt": requirements,
            f"{project_root}/.gitignore": gitignore,
            f"{project_root}/.github/workflows/ci.yml": ci_workflow,
            f"{project_root}/src/{pipeline_file}": response.python_code,
            f"{project_root}/tests/{test_file_name}": generated_test,
            f"{project_root}/sql/bronze_table.sql": response.sql_code,
            f"{project_root}/config/config.yaml": config,
            f"{project_root}/config/quality_rules.txt": "\n".join(
                response.quality_rules
            ),
            f"{project_root}/config/assumptions.txt": "\n".join(
                response.assumptions
            ),
        }