from copilot.models.bronze import (
    BronzeGenerationRequest,
    BronzeGenerationResponse,
)


class ProjectGenerator:
    """Generate project files from a Bronze Response."""

    @staticmethod
    def generate_files(
        request: BronzeGenerationRequest,
        response: BronzeGenerationResponse,
    ) -> dict[str, str]:
        """Return generated project files."""

        pipeline_name = (
            request.api_name
            .lower()
            .replace(" api", "")
            .replace(" ", "_")
        )
        
        pipeline_file = f"{pipeline_name}_ingestion.py"

        test_file_name = f"test_{pipeline_name}_ingestion.py"

        readme = f"""# {request.api_name} Bronze Pipeline

Generated by Enterprise Engineering Copilot.

## API

{request.api_name}

## Endpoint

{request.endpoint}

## Authentication

{request.authentication}

## Description

{request.description}

## Generated Files

- {pipeline_file} - Bronze ingestion pipeline
- {test_file_name} - Unit tests
- bronze_table.sql - Delta table definition
- config.yaml - Project configuration
- requirements.txt - Python dependencies
- quality_rules.txt - Data quality checks
- assumptions.txt - Pipeline assumptions

## Summary

{response.summary}
"""

        config = f"""api:
  name: {request.api_name}
  endpoint: {request.endpoint}
  authentication: {request.authentication}

bronze:
  catalog: default
  schema: bronze
  table: {pipeline_name}

retry:
  max_attempts: 3
  backoff_seconds: 5
"""
        
        requirements = """requests
pydantic
tenacity
pyspark
delta-spark
databricks-sdk
streamlit
fastapi
uvicorn
"""

        test_file = f"""import pytest


def test_{pipeline_name}_ingestion_placeholder():
    \"\"\"Placeholder test for generated Bronze ingestion pipeline.\"\"\"

    # TODO: Add ingestion pipeline tests.
    assert True
"""

        return {
            pipeline_file: response.python_code,
            test_file_name: test_file,
            "bronze_table.sql": response.sql_code,
            "README.md": readme,
            "config.yaml": config,
            "requirements.txt": requirements,
            "quality_rules.txt": "\n".join(response.quality_rules),
            "assumptions.txt": "\n".join(response.assumptions),
        }